"""Author-only story candidate. Does not change live packet sources or public copy."""
from pathlib import Path
import yaml

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'docs/story-pass-12-SPOILERS'

# These are individual scenes within one interrupted reception, not thirty errands.
OPPORTUNITY={
'01': "I told the service manager to hold Grant's announcement. We had no board vote on his terms. When the mounting problem stopped the unveiling, I tried to turn the wait in the salon into that vote. I had already sent the chair a forged resignation demand with Grant's signature on it. Grant caught me counting trustees beside his place setting. He called for the toast anyway. I had arranged a board challenge in the middle of my own fundraiser.",
'02': "The bowl's mounting problem stopped the unveiling. I carried the disputed label into the salon and put it in front of Grant. He wanted the ownership claim read while the object was hidden behind the curtain. I had removed that wording without approval and concealed the independent review from the board. He reached for the label; I held on to it. Several people were arguing by then. I was prepared to stop my own exhibition rather than read his claim.",
'03': "I had altered the certificate file. When Grant opened it in the salon, I tried to close the case before the waiting guests saw both versions. He read the refund figure aloud anyway. I offered a settlement and told him the firm could meet it. It couldn't. I tore up my first offer and kept the envelope. A conversation I had intended to keep between two dealers had become part of the reception.",
'04': "The kitchen wanted to know whether the museum would cover Grant's extra course. I said no. I had already made an unauthorized transfer to cover payroll, and he wanted his marble-wing expenses buried in it. During the wait in the salon, I took that addition off the payment schedule. Grant put it back. I pulled the ledger away from his leaking pen. The service manager went to deal with the kitchen dispute while we argued about who was paying.",
'05': "The mounting fault was real. I asked for the curtain closed and told Grant the bowl could not be unveiled. He demanded the insurance record instead. I had changed its treatment date, and I took his copy out of the display file before the crew could compare it with the photograph. He followed me into the salon calling the closure an excuse. I had applied the poison bottle's custody band before the walkthrough. I was now disputing the condition of a different object in front of the guests.",
'06': "I had put the warning in the program. The STAR was the performance he had taken from me. After the curtain closed, I set my rehearsal glass beside his donor glass and showed him how the apparent collapse was supposed to work. He had canceled the effect. I was still trying to get it into the closing show under my own name. I wanted the people standing there to see who had made it. I had not told the operator that I intended to restore the canceled scene.",
'07': "I turned the student painting toward the wall. When the unveiling stopped, Grant brought its sale notice into the salon and asked whether the famous painter would sign it. I had brought cash to buy the picture back. He offered to auction it instead. I took the notice off the tray beside his place and drew the replacement I wanted him to accept. The signature I had painted out years ago was mine. He made sure the waiting guests heard that part.",
'08': "Grant wanted to sign the naming agreement during the delay. I put my original opinion on the salon table before he could use the softened version as clearance. I had rewritten it to please him and failed to object when he called it approval. This time I read the qualification aloud. He pushed the page toward me for a signature. I pushed it back. I was trying to undo legal advice I had allowed him to misrepresent.",
'09': "We argued over the archive reference while the crew checked the mounting. I had corrected the exhibition citation, then admitted that one sentence in my own article went too far. Grant wanted the entire article withdrawn. I followed him into the salon because he was telling the waiting guests that I had conceded the ownership question. I corrected him in front of them. My error was real; the larger concession he described was not.",
'10': "I called the trustees and told one of them we already had the votes. We didn't. In the salon, Grant put the trust amendment next to his toast glass and asked me to sign where everyone could see. I pushed it back and said the family had rejected it. Another bluff. I wanted the signature ceremony stopped before the trustees compared stories. I was using the delay to assemble a revolt I had already announced as a victory.",
'11': "I ordered the salon camera unplugged for Grant's private negotiations. When the display closed and guests came in, that room was still unrecorded. I should have reversed the exception. Instead, I closed the door on the photographers and tried to keep the argument private. Grant was waving the signed instruction at me from beside his table. I had followed his order against policy and was now protecting the meeting that made it dangerous.",
'12': "My recorder was in the pocket of Grant's coat. He had taken it after I refused to name my source. During the wait, he hung the coat over the salon chair and went to argue about the display. I took the recorder back. I also moved his acquisition file aside because it was covering the coat pocket. He caught me with both the recording and the file in my hands. I said I was recovering my property. That left out the papers I had photographed.",
'13': "I pulled my old approval tag off the mounting. The crew thought I was clearing the fault; I was hiding the load figure I had signed. Then I stopped the work properly and kept the curtain closed. Grant argued with me in the salon about reopening it for his photograph. I unplugged the spare display lamp he was having brought in. I would not let the lighting be used to make the closed display look approved. I had concealed one unsafe decision while trying to prevent another.",
'14': "I blocked the alcove entrance before the mounting alert closed it. I had leaked the restitution talks without permission, and now I insisted on the loan terms being heard in the salon. Grant called the bowl his permanent gift. I put the delegation's objection where the board was about to sign. He tried to tear it out of the agreement. I took the agreement away from him. I had gone from leaking a negotiation to interrupting the signing it was meant to prevent.",
'15': "The auction invoice named my company. I had kept that connection out of the pitch. During the delay I made the lower-price offer in the salon, where Grant had to hear it in front of the other patrons. He brought up the board seat. I told him the offer would disappear if he blocked the appointment. That was a bargain I had not admitted to my partners. We were negotiating over his toast table while everyone waited for the curtain to reopen.",
'16': "I substituted a photocopy that omitted my handwritten exception from the old accession. Grant found the original and carried it into the salon. He wanted me to repeat its approval in front of the current board. I took back the photocopy and admitted that the promised export papers had never arrived. I had accepted an incomplete file in 1989. I was concealing that decision again until he made the missing line the subject of his toast.",
'17': "I disclosed my client's ceiling price to Grant. I then tried to recover my commission through an off-book subsidiary fee. During the delay, I put the private fee statement into his acquisition case while he was occupied with the naming argument. He noticed it and read the number to the room. I took the sheet back. The client had authorized neither the disclosure nor the replacement fee. I was trying to close the sale before either side compared invoices.",
'18': "I took the family textile down before Grant could call it his permanent gift. I had offered it elsewhere without getting the family consent either loan required. When guests moved to the salon, I carried it folded over my arm and refused to leave it on the donor table. Grant offered a purchase price. I said the cloth was not mine to sell. I had been rather slower to say it was not mine to promise.",
'19': "I changed the online catalog without permission after finding the reference I had copied too quickly. Grant wanted the old attribution restored before guests searched for it. In the salon I let people use my phone to read the corrected entry. I had not warned Art that it also challenged his published sentence. Grant asked which version I intended to defend. I kept the source register open. I was exposing my own shortcut and somebody else's claim in the same correction.",
'20': "I opened the sculpture's support panel so the crew could see the joint. I had changed the approved support and left the fabricator out of the credit. Grant was discussing his cheaper replacement in the salon when I came back. I picked up his empty glass and offered a toast to the worker whose name neither of us had put on the sculpture. I set it back. I wanted him embarrassed. I was also pretending I had been generous about credit all along.",
'21': "I stopped the assistant unpacking my replacement donation. I had sold the piece I promised. When the unveiling was delayed, Grant demanded that I bring the substitute into the salon for the donor photograph. I left it boxed and stood in front of its label. He asked the assistant for the packing list. I said the original was unavailable and tried to take the list away. It was sold, and I had come dressed to be thanked for giving it away.",
'22': "I interrupted the speech rehearsal with a line from my anonymous column. Grant recognized it. During the salon argument I recorded him promising to name the author, then stopped the phone before he reached the correction he had paid for. I had accepted that payment and edited the recording to conceal it. The waiting audience heard my joke; the public feed would miss the transaction. I wanted him to look ridiculous without letting the room see what I had sold him.",
'23': "I withheld the unpaid extra course and used a cheaper dessert supplier than the menu promised. The manager went to the kitchen to settle the payment dispute. I stayed at the salon table, where sauce had spilled over the invoice and the glass base. I moved the glass by its stem and cleaned the base before rescuing the invoice. Grant called it spoiled service. I told him the course stayed in the kitchen until somebody signed for the changes he had ordered.",
'24': "I delivered the boxed donor glass to the manager, then hid the frame crack under its packing blanket. The lift fault delayed the trolley. Once the mechanic released it, I brought the work through the salon while everyone was waiting on the display. Grant wanted an undamaged delivery record signed there. I left the blanket over the frame. I had concealed the crack and was hoping the photographs would be finished before anyone lifted that blanket.",
'25': "I put petition copies into the trustee folders and claimed the director supported it. I had not asked him. The mounting delay gave me a roomful of waiting trustees, so I collected signatures in the salon while Grant was trying to sign his gift. He took the petition from the table. I took it back and kept asking. I had used the staff mailing list without permission. I was now turning the donor reception into a meeting about the jobs his lounge would remove.",
'26': "Grant wanted the camera file and every print destroyed. I agreed to delete the file and kept a print. During the delay I retrieved it from the photographer's tray in the salon and put it in my own sleeve. He asked whether every copy was gone. I answered that the file had been deleted. The picture showed his meeting beside the shipping papers. I had given him a narrower promise than the one I intended him to hear.",
'27': "I put a protest sticker on Grant's jacket for the reception photograph. He tore it off. When guests gathered in the salon, I returned with the brochures despite promising to stay out of the presentation. I put a copy beside the glass for the donor photograph. He swept it off the table. I recovered it and kept distributing copies. I had broken my promise; he wanted the ownership questions removed along with the paper.",
'28': "Grant offered a price for my family's silence. I had withheld the letter about my grandfather's part in the sale. During the argument in the salon I tore up the offer and threw it into the fireplace. I then said I had brought all the family papers. I hadn't. The originals remained in my case. I wanted guests to see him buying silence and to miss the part of the history that would explain why I had considered his price.",
'29': "I let people hear my account of the property deal during the delay in the salon. A guest asked about the boundary, and I stopped the recording. I knew the parcel record contradicted the story. Grant had promised archive access if I left his version alone. I deleted the public take and kept it on the recorder. I was correcting him at his own reception while trying to hide how long I had known I needed that correction.",
'30': "I hid an unauthorized blackout in the naming sequence. The real mounting alert triggered the safety override before my cue could run. I came into the salon carrying the canceled program and told Grant the closing spectacle was still ready. It wasn't. The operator had stopped the sequence, and I had intended to restore the interruption without telling them. I straightened the donor place setting for the photograph while we argued about putting his lettering back. I was being paid to stage an evening I wanted to interrupt.",
}

SUSPICION={
'01':'forged resignation demand','02':'removed that wording without approval','03':'altered the certificate file',
'04':'unauthorized transfer','05':'changed its treatment date','06':'put the warning in the program',
'07':'turned the student painting toward the wall','08':'rewritten it to please him','09':'one sentence in my own article went too far',
'10':'Another bluff','11':'ordered the salon camera unplugged','12':'papers I had photographed',
'13':'hiding the load figure','14':'leaked the restitution talks','15':'kept that connection out of the pitch',
'16':'substituted a photocopy','17':"disclosed my client's ceiling price",'18':'offered it elsewhere',
'19':'changed the online catalog without permission','20':'left the fabricator out of the credit',
'21':'sold the piece I promised','22':'edited the recording to conceal it','23':'cheaper dessert supplier',
'24':'hid the frame crack','25':'claimed the director supported it','26':'kept a print',
'27':'broken my promise','28':'withheld the letter','29':'deleted the public take','30':'hid an unauthorized blackout',
}

# Method answers explain the particular act exposed in Opportunity. Exact receipts
# are delayed until this round. Ordinary corroboration is not a complete alibi.
INNOCENT_METHOD={
'01':"The resignation demand was forged; the chair had never seen Grant sign it. I sent her my marked draft after the argument. She refused to call a vote in the salon, so I took the call in the office. Her answer came before the toast. I did not get the board rebellion I had advertised. I got a written instruction to stop using her name as support for it. That email and the draft explain the letter I circulated.",
'02':"The independent review gives the missing permit number. It was written before tonight's argument. The label I held in the salon copied that finding, and the registrar photographed both labels before the unveiling. I had hidden the review from the board. I could still put the permit question in front of them, however embarrassing the concealment was for me. The red marks on the label are correction ink; the original is still in the registrar's file.",
'04':"The extra course was held on my instruction. The kitchen order records it separately from payroll. Grant's marble-wing addition is on the ledger page I pulled out; his leaking pen stained the schedule underneath. The bank already had the salary instruction and no board authorization from me. I can establish where the red stain came from. I cannot turn that instruction into an authorized transfer by saying people needed paying.",
'05':"The mounting crack appears in the crew's photograph and in my stop-work finding. The treatment date I changed is on a separate insurance copy. The original photograph is earlier and survived my alteration. I issued the closure before the naming argument, and the rigger kept the notice. My unused red foil-backed strips are custody-band stock. The condition record shows the band I applied before the walkthrough. That stock and the real mounting fault do not excuse the false date.",
'06':"The rehearsal glass has PROP painted underneath it. It is plain glass; Grant's gift glass has the museum star etched into its base. Mine went back in the padded prop case, and the manager's rehearsal photograph shows it beside the empty jacket on its stand. The effect used light and the jacket. Nobody was meant to drink anything. The foil-backed red scraps in my program are confetti offcuts. I had planned an unauthorized performance, and the case contains the equipment for it.",
'08':"The original opinion and the rewrite both reserve the ownership question. My assistant emailed the original before tonight's meeting; the attachment has the paragraph Grant wanted gone. In the salon I refused the signature line under the claim of settled title. He tore that corner, and the torn page is still with the agreement. I should have made the qualification public when I first rewrote it. The file records the compromise and the objection I finally made.",
'11':"The camera instruction bears Grant's signature. The technician's work order says the cable was unplugged; the lighting alert did not cause it. I let the exception continue when people entered the salon. The gallery-door camera remained running and records the crowd coming through. It provides no view of the tabletop. I can show whose order I followed and which room I left unrecorded. That is a security failure I am responsible for.",
'12':"My editor had the earlier recording before Grant confiscated the recorder. The recovered file matches it, including the offer to withdraw the injunction for my source's name. The photograph I took shows the shipping cover, not the missing export permit itself. I would have liked it to prove more. I took back the recorder, concealed the source and photographed a file without permission. My editor's copies distinguish those decisions from the factual correction I had already sent.",
'13':"The first approval tag has my load figure. The stop-work sheet replaces it and records the mounting crack. The rigger kept both after I tried to remove the first. I unplugged the spare display lamp; Barb's camera cable was a separate work order. The crew's inspection pictures show which support we were checking. I had helped create the unsafe setup. Keeping that setup closed was the decision I should have made before guests arrived.",
'14':"The delegation's signed draft calls the bowl a loan and reserves the right to recall it. My leaked copy has that same clause, though the partners had not authorized its release. The agreement I took from Grant still has the clause crossed out in his hand. I interfered with the signing. The people I represent can identify the terms I was defending and the confidence I broke. The curtain closure came from the mounting notice, not from a device I brought.",
'20':"I lifted Grant's empty glass for the mock toast and put it back. The dust on my cuffs was plaster from opening the support panel; the crew's photographs show me doing that work. The fabricator's drawing identifies the worker I omitted from the label. I brought it out after the argument. That is how I made the hidden support and the missing credit public. The repair sample still sits beside the panel. I was trying to defend work I had failed to credit properly.",
'23':"The red wrapper in my folder is printed with the dessert supplier's name on its back. The foil-backed custody stock is different material. The sauce on the invoice matches the kitchen's retained batch, which tested clear. I handled the glass by its stem to clean the base. I withheld the extra course on the payment instruction and concealed the cheaper dessert supplier. The order and the stained invoice show both. The kitchen dispute was real, and I made it part of the reception.",
'25':"The education staff kept my mailing-list request and the petition replies. I sent the copies before receiving permission. The director's written answer corrects my claim that he supported the campaign; the signatures are genuine. Grant folded his gift terms over the petition, and both pages have the same staple hole from the trustee folder. That is what I took back from him. I used an unauthorized mailing and a false endorsement to argue against real job cuts.",
'28':"The papers I burned were a photocopy of the silence offer. The family solicitor kept the original and a transcript of my grandfather's letter. I brought the original offer in my case and hid the letter. The surviving pages explain the price Grant named and the part I omitted. I was asking guests to condemn his account while protecting mine. I will supply the whole correspondence. The copy in the fireplace was evidence I wanted the room to forget.",
'30':"The console log shows the safety override canceled my blackout. The electrician retained the cue sheet I hid it in. Barb's camera disconnection was a separate system and order. I reset the napkin and program for the photograph; I left the glass in place. My folder contains foil-backed red confetti offcuts from the shared materials stock, with the unused effect packet. The promised closing show could not run. I concealed that cancellation because admitting it would expose what I had put in the sequence.",
}

def make():
    if (OUT/'investigation_copy.yaml').exists():
        raise SystemExit('Pass 12 authored YAML already exists. This precursor must not overwrite subsequent edits or frozen trials.')
    OUT.mkdir(parents=True,exist_ok=True)
    data=yaml.safe_load((ROOT/'source/investigation_copy.yaml').read_text(encoding='utf-8'))
    for r in data['characters']:
        ident=r['id'];r['hearings']['where_innocent']=OPPORTUNITY[ident]
        r['hearings']['where_murderer']=OPPORTUNITY[ident]
        if ident in INNOCENT_METHOD:r['hearings']['evidence_innocent']=INNOCENT_METHOD[ident]
        r['suspicion']=SUSPICION[ident]
        if r['exclusion']['family']=='contextual':
            r['exclusion']['activity_premise']=OPPORTUNITY[ident]
            r['exclusion']['anchors']=[r['hearings']['evidence_innocent']]
            r['exclusion']['claim_fragments']=[{'round':'where','text':OPPORTUNITY[ident]}, {'round':'evidence','text':r['hearings']['evidence_innocent']}]
        else:
            r['exclusion']['activity_premise']=OPPORTUNITY[ident]
            r['exclusion']['anchors']=[r['hearings']['evidence_innocent']]
            r['exclusion']['claim_fragments']=[{'round':'where','text':OPPORTUNITY[ident]}, {'round':'evidence','text':r['hearings']['evidence_innocent']}]
    (OUT/'investigation_copy.yaml').write_text(yaml.safe_dump(data,sort_keys=False,allow_unicode=True,width=105),encoding='utf-8')

if __name__=='__main__':make()
